-- WORKBOOK2 FUNCTION

/** 1번 **/

SELECT 
	STUDENT_NO AS 학번,
	STUDENT_NAME AS 이름,
	ENTRANCE_DATE AS 입학년도
FROM TB_STUDENT 
WHERE DEPARTMENT_NO = '002'
ORDER BY ENTRANCE_DATE ASC;


/** 2번 **/

SELECT PROFESSOR_NAME, PROFESSOR_SSN
FROM TB_PROFESSOR
WHERE LENGTH(PROFESSOR_NAME) > 3 OR
LENGTH(PROFESSOR_NAME) < 3;

/** 3번 **/

SELECT 
	PROFESSOR_NAME AS 교수이름,
	FLOOR(MONTHS_BETWEEN(SYSDATE, TO_DATE('19'||SUBSTR(PROFESSOR_SSN,0,6), 'YYYYMMDD'))/12) AS 나이
FROM TB_PROFESSOR
ORDER BY 나이 ASC;
/** 나이 구하기
FLOOR(MONTHS_BETWEEN(
		SYSDATE, TO_DATE('2001.03.20', 'YYYY.MM.DD') 
	) / 12) AS "만 나이"
**/

/** 4번 **/

SELECT 
	SUBSTR( PROFESSOR_NAME, 2 ) as 이름
FROM TB_PROFESSOR 


/** 5번 **/
SELECT 
	STUDENT_NO, 
	STUDENT_NAME
FROM TB_STUDENT 
WHERE
	TO_NUMBER(TO_CHAR(ENTRANCE_DATE,'YYYY'))-TO_NUMBER('19'||SUBSTR(STUDENT_SSN, 0, 2)) > 19 ;
	 

/*CEIL(
		(SYSDATE 
		- TO_DATE('2001.03.20', 'YYYY.MM.DD')) / 365 + 1
	) AS "한국식 나이",
 * */	


/** 6번 **/

SELECT 
	STUDENT_NO,
	STUDENT_NAME, 
FROM TB_STUDENT 
WHERE STUDENT_NO NOT LIKE 'A%';


/** 7번 **/
SELECT 
	ROUND(AVG(POINT),1)
FROM TB_GRADE 
WHERE STUDENT_NO ='A517178'
GROUP BY STUDENT_NO;

/** 8번 **/
SELECT 
	DEPARTMENT_NO AS 학과번호,
	COUNT(DEPARTMENT_NO) AS "학생수(명)"
FROM TB_STUDENT 
GROUP BY DEPARTMENT_NO
ORDER BY DEPARTMENT_NO ASC;


/** 9번 **/
SELECT 
	COUNT(*)
FROM TB_STUDENT 
GROUP BY COACH_PROFESSOR_NO
HAVING COACH_PROFESSOR_NO IS NULL;

/** 10번 **/
SELECT 
	SUBSTR(TERM_NO,0,4) AS 년도,
	ROUND(AVG(POINT),1) AS "년도 별 평점"
FROM TB_GRADE 
WHERE STUDENT_NO ='A112113'
GROUP BY SUBSTR(TERM_NO,0,4)
ORDER BY 년도 ASC;

/** 11번 **/
SELECT 
	DEPARTMENT_NO AS 학과코드명,
	SUM(DECODE(
		ABSENCE_YN,
		'Y', TO_NUMBER(1),
		'N', TO_NUMBER(0) 
	)) AS "휴학생 수"
FROM TB_STUDENT 
GROUP BY DEPARTMENT_NO
ORDER BY DEPARTMENT_NO ASC;


-- GPT의 복잡한 답을 보았다.
SELECT 
	D.DEPARTMENT_NO AS "학과코드명",
	COALESCE(TO_CHAR(COUNT(S.ABSENCE_YN)),'0') AS "휴학생 수"
FROM TB_DEPARTMENT D
LEFT JOIN
	TB_STUDENT S ON D.DEPARTMENT_NO = S.DEPARTMENT_NO  AND S.ABSENCE_YN = 'Y'
GROUP BY 
	D.DEPARTMENT_NO 
ORDER BY 
	D.DEPARTMENT_NO ASC;



/**12번**/
SELECT 
	STUDENT_NAME ,
	COUNT(*) 
FROM TB_STUDENT 
GROUP BY STUDENT_NAME 
HAVING COUNT(STUDENT_NAME) > 1
ORDER BY STUDENT_NAME ASC;


/** 13 **/

SELECT 
	SUBSTR(TERM_NO,0,4) AS 년도,
 	SUBSTR(TERM_NO,5,2) AS 학기,
	ROUND(AVG(POINT),1) AS 평점
FROM TB_GRADE  
WHERE STUDENT_NO = 'A112113'
GROUP BY ROLLUP(SUBSTR(TERM_NO,0,4), SUBSTR(TERM_NO,5,2)); 











	